# Generated by Django 4.0.6 on 2022-08-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codesApi')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
            ],
        ),
        migrations.AlterField(
            model_name='qrcodeapi',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codesApi'),
        ),
    ]
