# Generated by Django 4.0.6 on 2022-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApi', '0002_testmodel_alter_qrcodeapi_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeapi',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
    ]
