# Generated by Django 4.0.6 on 2022-08-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApi', '0003_alter_qrcodeapi_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeapi',
            name='bg_color',
            field=models.CharField(choices=[('WHITE', 'white'), ('BLUE', 'blue'), ('RED', 'red'), ('YELLOW', 'yellow')], max_length=50, null=True),
        ),
    ]
