# Generated by Django 4.0.6 on 2022-08-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrApi', '0004_qrcodeapi_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeapi',
            name='qr_color',
            field=models.CharField(choices=[('WHITE', 'white'), ('BLUE', 'blue'), ('RED', 'red'), ('YELLOW', 'yellow'), ('BLACK', 'black')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeapi',
            name='bg_color',
            field=models.CharField(choices=[('WHITE', 'white'), ('BLUE', 'blue'), ('RED', 'red'), ('YELLOW', 'yellow'), ('BLACK', 'black')], max_length=50, null=True),
        ),
    ]
