# Generated by Django 4.0.6 on 2022-08-07 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qrCode_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_code_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
